version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=orangehrm
      - MYSQL_USER=orangehrm
      - MYSQL_PASSWORD=orangehrm_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - orangehrm-network

  orangehrm:
    image: orangehrm/orangehrm:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=orangehrm
      - MYSQL_USERNAME=orangehrm
      - MYSQL_PASSWORD=orangehrm_password
    volumes:
      - orangehrm_data:/var/www/html
    depends_on:
      - db
    networks:
      - orangehrm-network

networks:
  orangehrm-network:
    driver: bridge

volumes:
  db_data:
  orangehrm_data:
